In [1]:
import numpy as np
np.set_printoptions(precision=2)

# Matrixfaktorisierung mit SVD

Die Singulärwertzerlegung nimmt eine Matrix R und teilt sie in 3 Faktoren:
$$R=U\cdot D\cdot V$$

In [9]:
np.linalg.svd?

In [10]:
r = np.matrix([[5,3,4],[0,2,4],[4,2,0]])
r

matrix([[5, 3, 4],
        [0, 2, 4],
        [4, 2, 0]])

In [11]:
#Beschreibe die Matrix r durch k latente Faktoren, 
#bzw. als eine Matrix rhat vom Rang k
k=1

In [12]:
U,S,V = np.linalg.svd(r)
if k==1:
    S = np.matrix(np.diag([S[0],0,0]))
elif k==2:
    S = np.matrix(np.diag([S[0],S[1],0]))
elif k==3:
    S = np.matrix(np.diag(S))
U,S,V

(matrix([[-0.82,  0.03, -0.57],
         [-0.37, -0.78,  0.51],
         [-0.43,  0.63,  0.65]]), matrix([[ 8.57,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ]]), matrix([[-0.68, -0.48, -0.56],
         [ 0.66, -0.06, -0.75],
         [-0.33,  0.88, -0.35]]))

Diese Zerlegung kann natürlich auch in eine Zerlegung in zwei Faktoren umgewandelt werden:

In [13]:
P = U*np.sqrt(S)
Q = np.sqrt(S)*V

**Aufgaben:**
- Welchen Rang hat die Matrix P*Q?
- Wieviele Floats müssen für P und Q gespeichert werden? Wieviele für P*Q? Wieviele für R?

In [14]:
rhat=np.around(P*Q,7)
rhat

array([[ 4.8 ,  3.35,  3.94],
       [ 2.17,  1.51,  1.77],
       [ 2.5 ,  1.74,  2.05]])

Vergleiche mit der ursprünglichen Matrix:

In [15]:
r

matrix([[5, 3, 4],
        [0, 2, 4],
        [4, 2, 0]])

In [16]:
e = r-rhat
e

matrix([[ 0.2 , -0.35,  0.06],
        [-2.17,  0.49,  2.23],
        [ 1.5 ,  0.26, -2.05]])

In [17]:
e2=np.multiply(e,e)
#print(e2)
e2=np.sum(e2)
#Fehler e^2=sum (rhat - r)^2
e2

16.559832942885361

1. **Aufgabe:** - Wieviele Einträge haben die Matrizen r, p und q?

In [104]:
import scipy.sparse
R_sparse = scipy.sparse.csr_matrix?

In [ ]:
R_sparse = scipy.sparse.csr_matrix

In [107]:
NrRows=10
NrCols=12
density=0.2
MaxRating=3

In [108]:
R_sparse=np.around(MaxRating*scipy.sparse.rand(NrRows,NrCols,density=density,format='csr'))

In [109]:
R_sparse.todense()

matrix([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  2.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  0.,  0.,  3.,  0.,  0.,  0.,  1.,  0.,  2.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  3.,  0.,  0.,  1.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])