In [1]:
import sklearn

In [2]:
import numpy as np
k=2
X = np.array([(1,2),(2,3),(5,7)])
y = np.array([0,1,0])
t = np.array([1.5,2.8])

In [4]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
#KNeighborsClassifier?

In [9]:
clf = KNeighborsClassifier(n_neighbors=2)

In [10]:
!ls
%cd

Bias_Varianz_Verallgemeinerung.ipynb
Cheat_Sheets.zip
Installationstest.ipynb
KNN_Musterlösung.ipynb
KNN_Musterlösung.ipynb.gpg
Lernkurven_KNN_Arbeitsblatt.ipynb
Linear_Regression_Overfitting_Arbeitsblatt.ipynb
Linear_Regression_Overfitting.ipynb
myKNN.ipynb
Numpy_KNN_data.tar.gz
Overfitting_DecisionTree.ipynb
PVA1.py
Schnell_mal_KNN_Kaggle_Submission.ipynb
Scikit-Learn_Beispiel.ipynb
scikitlearn_Beispiel.py
Slides_PVA1.pdf
test.csv
train.csv
Untitled.ipynb


In [11]:
import pandas as pd

In [24]:
dftrain = pd.read_csv('train.csv',header=None)
dftrain.columns=['x1','x2','y']
dftrain

x1  x2  y
0   0   1  1
1   1   0  1
2   1   1  1
3   1   2  1
4   2   2  1
5   2   3  0
6   3   3  0
7   4   3  0
8   3   8  0

In [34]:
dftest = pd.read_csv('test.csv',header=None)
dftest.columns=['x1','x2']

dftrain.y

0    1
1    1
2    1
3    1
4    1
5    0
6    0
7    0
8    0
Name: y, dtype: int64

In [30]:
df.values

array([[1, 4],
       [6, 2],
       [0, 0],
       [3, 1],
       [1, 3]])

In [41]:
X = dftrain[['x1','x2']].values
y = dftrain[['y']].values

y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0]])

In [46]:
y==1

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False]])

In [47]:
X[(y==1).ravel()]

array([[0, 1],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 2]])

In [50]:
X[X[:,0]>2,:]

array([[3, 3],
       [4, 3],
       [3, 8]])

In [53]:
y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0]])

In [60]:
clf.fit(X,y.reshape(-1))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [58]:
y.ravel().shape

(9,)

In [68]:
clf.predict(t.reshape(-1,2))

array([0])

In [67]:
t.reshape(-1,2)

array([[1.5, 2.8]])