In [1]:
# Import für Beispieldatensätze
from sklearn import datasets
# Erzeugen des Iris-Datensatzes
iris = datasets.load_iris()

In [2]:
# Import und Erzeugung eines DecisionTree Klassierers
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

Alternativ kann ein NaiveBayes Klassierer verwendet werden

    from sklearn.naive_bayes import GaussianNB
    clf = GaussianNB()

Weitere Alternative: Support Vector Maschine  

    from sklearn.svm import SVC
    clf = SVC()

Die Variable clf für den Klassierer ist nun definiert und kann gebraucht werden;
der folgende Code funktioniert für alle Typen von Klassierern gleich.

Der Klassierer wird nun mit dem Iris-Datensatz ohne die letzten zwei Elemente trainiert.

In [63]:
Xtrain = iris.data[:-2]
ytrain = iris.target[:-2]

In [64]:
ytrain = ytrain.reshape(-1,1)

In [65]:
clf.fit(X,y) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

Der Klassierer soll nun die letzten zwei Elemente des Datensatzes klassieren

In [66]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [67]:
Xtest = iris.data[[-1,-2],:].reshape(2,-1)
ytest = iris.target[[-1,-2]]

In [68]:
Xtest.shape

(2, 4)

In [69]:
clf.predict(Xtest)

array([2, 2])

In [70]:
# Zum Vergleich der effektive Typ des letzten Elementes des Datensatzes
ytest

array([2, 2])

Mit Hilfe der CrossValidation soll der Klassierer getestet werden.  
http://scikit-learn.org/stable/modules/cross_validation.html  
Import des Package für die CrossValidation

In [71]:
from sklearn import cross_validation

# Aufspalten des Datensatzes in Trainings- und Testdaten (die Elemente werden gemischt)
# test_size ist entweder ein float zwischen 0.0 und 1.0 (Anteil) oder ein ganze Zahl
data_train, data_test, target_train, target_test = \
    cross_validation.train_test_split(iris.data, iris.target, test_size=0.2)

/home/toedtli/.virtualenvs/v_py3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [72]:
# Trainieren des Klassifizierers mit den Trainingsdaten
clf.fit(data_train, target_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [75]:
# Klassierungen der testdaten
clf.predict(data_test)

array([2, 0, 1, 2, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 0, 2, 1, 2, 2, 1,
       1, 1, 2, 1, 2, 0, 2, 1])

In [76]:
# Vergleich der vorhergesageten Klassen mit den effektiven Klassen
target_test

array([2, 0, 1, 2, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 0, 2, 1, 2, 2, 1,
       1, 1, 2, 1, 2, 0, 2, 2])

In [81]:
# Bestimmung der Genauigkeit ders Klassierers auf den Testdaten
clf.score?
clf.score(data_test, target_test)

0.9666666666666667

### Für Cracks: Verwendung von Iteratoren zur CrossValidation

In [82]:
# KFold: Datensatz wird in n Teile aufgeteilt,
# jeweils n-1 viele Teile als Trainingsdaten und
# ein teil als Testdaten.
# Die Funktion teilt nicht den Datensatz auf, sondern erzeugt
# einen Iterator mit entsprechende Indexmengen.
for trainIndices, testIndices in cross_validation.KFold(len(iris.data), n_folds=3) :
    clf.fit(iris.data[trainIndices], iris.target[trainIndices])
    print(clf.score(iris.data[testIndices], iris.target[testIndices]))

0.0
0.0
0.0


Das Ergebnis ist unbrauchbar, da der Iris-Datensatz nach Klasse sortiert ist
und KFold nicht mischt, wenn man es nicht verlangt.  
Besser:

In [83]:
for trainIndices, testIndices in cross_validation.KFold(len(iris.data), n_folds=3, shuffle=True) :
    clf.fit(iris.data[trainIndices], iris.target[trainIndices])
    print(clf.score(iris.data[testIndices], iris.target[testIndices]))

0.88
0.96
0.92


Statt for-Schleife selber zu schreiben, kann man die folgende Funktion verwenden:

In [84]:
print(cross_validation.cross_val_score(clf, iris.data, iris.target, \
                cv=cross_validation.KFold(len(iris.data), n_folds=3, shuffle=True)))

[0.98 0.96 0.94]


Eine Alternative zu KFold ist LeaveOneOut 

In [88]:
cvscores = cross_validation.cross_val_score(clf, iris.data, iris.target, 
                cv=cross_validation.LeaveOneOut(len(iris.data)))
cvscores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
import numpy as np
np.mean(cvscores)

0.96